version: '3'

services:
  node-typescript:
    container_name: dp_activities-node_typescript
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/usr/app:delegated
    tty: true
    user: node:node
    command: yarn start
